# Generated by Django 5.2.1 on 2025-06-07 08:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название адреса')),
                ('address_line', models.CharField(help_text='Например, г. Москва, ул. Примерная, д. 10', max_length=255, verbose_name='Адрес')),
                ('reception_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер телефона')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название Ценности')),
                ('description', models.CharField(max_length=100, verbose_name='Описание Ценности')),
            ],
            options={
                'verbose_name': 'Ценность',
                'verbose_name_plural': 'Ценности',
            },
        ),
        migrations.CreateModel(
            name='MedicalDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Направление')),
                ('description', models.CharField(max_length=500, verbose_name='Описание направления')),
            ],
            options={
                'verbose_name': 'Направление в медицине',
                'verbose_name_plural': 'Направления в медицине',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('completed', 'Услуга оказана')], default='pending', max_length=50, verbose_name='Статус')),
                ('appointment_date', models.DateTimeField(verbose_name='Дата приёма')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус записи')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.addresshospital', verbose_name='Адрес клиники')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Рекомендации')),
                ('general_comments', models.TextField(blank=True, null=True, verbose_name='Общие комментарии')),
                ('appointment', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.appointment', verbose_name='Запись')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь создавший этот экземпляр модели')),
            ],
            options={
                'verbose_name': 'Результат диагностики',
                'verbose_name_plural': 'Результаты диагностики',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='medical/', verbose_name='Фотография')),
                ('specialization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Специальность')),
                ('experience', models.CharField(blank=True, max_length=255, null=True, verbose_name='Стаж работы')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь создавший этот экземпляр модели')),
                ('medical_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.medicaldirection', verbose_name='Медицинское направление')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктора',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.doctors', verbose_name='Доктор'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Тема обращения')),
                ('feedback', models.CharField(max_length=500, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время создания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь создавший этот экземпляр модели')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_from_the_main_page', models.TextField(blank=True, null=True, verbose_name='Информация с главной страницы')),
                ('image_the_main_page', models.ImageField(blank=True, null=True, upload_to='medical/', verbose_name='Фото с главной страницы')),
                ('company_history', models.TextField(blank=True, null=True, verbose_name='История компании со страницы "О компании"')),
                ('mission', models.CharField(blank=True, max_length=100, null=True, verbose_name='Миссия со страницы "О компании"')),
                ('purposes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цели со страницы "О компании"')),
                ('image_from_the_company', models.ImageField(blank=True, null=True, upload_to='medical/', verbose_name='Фото со страницы "О компании"')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес центральной клиники')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь создавший этот экземпляр модели')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информации',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название услуги')),
                ('description', models.CharField(max_length=500, verbose_name='Описание услуги')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('medical_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='medical.medicaldirection')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь создавший этот экземпляр модели')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отзыв')),
                ('rate', models.CharField(choices=[('5', 'Все отлично!'), ('4', 'Все хорошо.'), ('3', 'Есть замечания'), ('2', 'Не устроило'), ('1', 'Категорически не устроило')], max_length=100, verbose_name='Количество звезд')),
                ('doctors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.doctors', verbose_name='Доктор')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, оставивший отзыв')),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.services', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.services', verbose_name='Услуга'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение')),
                ('norm', models.CharField(blank=True, max_length=255, null=True, verbose_name='Норма')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('diagnostic_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='medical.diagnosticresults')),
            ],
        ),
    ]
