# Generated by Django 5.2.1 on 2025-05-18 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Пациент', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosticresults',
            name='appointment',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.appointment', verbose_name='Запись'),
        ),
        migrations.AddField(
            model_name='diagnosticresults',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Пользователь создавший этот экземпляр модели', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctors',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Пользователь создавший этот экземпляр модели', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.doctors'),
        ),
        migrations.AddField(
            model_name='information',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Пользователь создавший этот экземпляр модели', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Пользователь, оставивший отзыв', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctors',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.reviews', verbose_name='Отзывы на врача'),
        ),
        migrations.AddField(
            model_name='services',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Пользователь создавший этот экземпляр модели', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.services'),
        ),
    ]
