# Generated by Django 5.2.1 on 2025-05-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='purposes',
            field=models.CharField(default=None, help_text='Цели со страницы "О компании"', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='information',
            name='mission',
            field=models.CharField(help_text='Миссия со страницы "О компании"', max_length=100),
        ),
    ]
