# Generated by Django 5.2.1 on 2025-05-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='company_history',
            field=models.TextField(blank=True, null=True, verbose_name='История компании со страницы "О компании"'),
        ),
        migrations.AlterField(
            model_name='information',
            name='text_from_the_main_page',
            field=models.TextField(blank=True, null=True, verbose_name='Информация с главной страницы'),
        ),
    ]
