# Generated by Django 5.2.1 on 2025-05-22 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_doctors_avatar_doctors_patronymic'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Направление')),
                ('description', models.CharField(max_length=500, verbose_name='Описание направления')),
            ],
        ),
        migrations.AlterField(
            model_name='doctors',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='medical/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='medical_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.medicaldirection'),
        ),
        migrations.AddField(
            model_name='services',
            name='medical_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.medicaldirection'),
        ),
    ]
