# Generated by Django 5.2.1 on 2025-05-18 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(verbose_name='Дата приёма'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='diagnosticresults',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь создавший этот экземпляр модели'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Стаж работы'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь создавший этот экземпляр модели'),
        ),
        migrations.AlterField(
            model_name='information',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес клиники'),
        ),
        migrations.AlterField(
            model_name='information',
            name='information',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Главная информация'),
        ),
        migrations.AlterField(
            model_name='information',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='information',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь создавший этот экземпляр модели'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rate',
            field=models.CharField(choices=[('5', 'Все отлично!'), ('4', 'Все хорошо.'), ('3', 'Есть замечания'), ('2', 'Не устроило'), ('1', 'Категорически не устроило')], max_length=100, verbose_name='Количество звезд'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, оставивший отзыв'),
        ),
        migrations.AlterField(
            model_name='services',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь создавший этот экземпляр модели'),
        ),
    ]
