# Generated by Django 5.2.1 on 2025-05-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_alter_information_company_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отзыв'),
        ),
    ]
