# Generated by Django 5.2.1 on 2025-05-18 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('medical', '0003_alter_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.doctors',
                                    verbose_name='Доктор'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.services',
                                    verbose_name='Услуга'),
        ),
    ]
