# Generated by Django 5.2.1 on 2025-05-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_feedback_created_at_feedback_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='message',
            new_name='feedback',
        ),
    ]
