# Generated by Django 5.2.1 on 2025-05-22 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_medicaldirection_alter_doctors_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicaldirection',
            options={'verbose_name': 'Направление в медицине', 'verbose_name_plural': 'Направления в медицине'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.doctors', verbose_name='Доктор'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.services', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='services',
            name='medical_direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='medical.medicaldirection'),
        ),
    ]
