# Generated by Django 5.2.1 on 2025-05-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_alter_medicaldirection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус записи'),
        ),
    ]
