# Generated by Django 5.2.1 on 2025-05-19 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_rename_message_feedback_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticresults',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medical.doctors', verbose_name='Доктор'),
            preserve_default=False,
        ),
    ]
