# Generated by Django 5.2.1 on 2025-05-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_diagnosticresults_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='company_history',
            field=models.CharField(max_length=500, verbose_name='История компании со страницы "О компании"'),
        ),
        migrations.AlterField(
            model_name='information',
            name='mission',
            field=models.CharField(max_length=100, verbose_name='Миссия со страницы "О компании"'),
        ),
        migrations.AlterField(
            model_name='information',
            name='purposes',
            field=models.CharField(max_length=100, verbose_name='Цели со страницы "О компании"'),
        ),
        migrations.AlterField(
            model_name='information',
            name='text_from_the_main_page',
            field=models.CharField(max_length=500, verbose_name='Информация с главной страницы'),
        ),
    ]
