# Generated by Django 5.2.1 on 2025-05-23 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_appointment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='medical_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.medicaldirection', verbose_name='Медицинское направление'),
        ),
    ]
