# Generated by Django 5.2.1 on 2025-05-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_alter_doctors_medical_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('completed', 'Услуга оказана')], default='pending', max_length=50, verbose_name='Статус'),
        ),
    ]
