# Generated by Django 5.2.1 on 2025-05-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_services_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='cardiology',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кардиология'),
        ),
        migrations.AddField(
            model_name='information',
            name='description_of_services',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Подробное описание услуг'),
        ),
        migrations.AddField(
            model_name='information',
            name='pediatrics',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Педиатрия'),
        ),
        migrations.AlterField(
            model_name='information',
            name='company_history',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='История компании со страницы "О компании"'),
        ),
        migrations.AlterField(
            model_name='information',
            name='mission',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Миссия со страницы "О компании"'),
        ),
        migrations.AlterField(
            model_name='information',
            name='purposes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Цели со страницы "О компании"'),
        ),
        migrations.AlterField(
            model_name='information',
            name='text_from_the_main_page',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Информация с главной страницы'),
        ),
    ]
