# Generated by Django 5.2.1 on 2025-05-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticresults',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='diagnosticresults',
            name='results',
        ),
        migrations.AddField(
            model_name='diagnosticresults',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='diagnosticresults',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='diagnosticresults',
            name='norm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Норма'),
        ),
        migrations.AddField(
            model_name='diagnosticresults',
            name='recommendations',
            field=models.TextField(blank=True, null=True, verbose_name='Рекомендации'),
        ),
        migrations.AddField(
            model_name='diagnosticresults',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение'),
        ),
    ]
