# Generated by Django 5.2.1 on 2025-05-19 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0008_information_cardiology_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='reviews',
        ),
        migrations.AddField(
            model_name='reviews',
            name='doctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.doctors', verbose_name='Доктор'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.services', verbose_name='Услуга'),
        ),
    ]
