# Generated by Django 5.2.1 on 2025-05-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0008_remove_diagnosticresults_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticresults',
            name='general_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Общие комментарии'),
        ),
    ]
