# Generated by Django 5.2.1 on 2025-05-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_remove_diagnosticresults_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='image_from_the_company',
            field=models.ImageField(blank=True, null=True, upload_to='medical/', verbose_name='Фото со страницы "О компании"'),
        ),
        migrations.AddField(
            model_name='information',
            name='image_the_main_page',
            field=models.ImageField(blank=True, null=True, upload_to='medical/', verbose_name='Фото с главной страницы'),
        ),
    ]
