# Generated by Django 5.2.1 on 2025-05-23 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_diagnosticresults_general_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticresults',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='diagnosticresults',
            name='name',
        ),
        migrations.RemoveField(
            model_name='diagnosticresults',
            name='norm',
        ),
        migrations.RemoveField(
            model_name='diagnosticresults',
            name='value',
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение')),
                ('norm', models.CharField(blank=True, max_length=255, null=True, verbose_name='Норма')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('diagnostic_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='medical.diagnosticresults')),
            ],
        ),
    ]
