# Generated by Django 5.2.1 on 2025-05-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_information_image_from_the_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresshospital',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='addresshospital',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
